### ISSUE TITLE
oom_disabled not working

### ISSUE THREAD

**Issue by Talhazzers** [pterodactyl/whmcs#110] opened 2022-01-05 17:33 UTC
OOM is always turned off on install. oom_disabled doesn't work.

**Comment by Software-Noob** [comment] 2022-01-05 17:40
Show the value, and your module debug logs for the server creation request. It would be disabled on the panel by default unless you overwrite it to false

**Comment by Talhazzers** [comment] 2022-01-05 19:07
`"oom_disabled":false,"` on module debug logs. OOM is not marked as disabled but when server is created OOM is disabled on server.

**Comment by Software-Noob** [comment] 2022-02-17 10:28
Can you please share the module logs and the order template because I can't reproduce this

**Comment by TrixterTheTux** [comment] 2022-05-15 07:20
This is due to the panel ignoring the option, which as far as I'm aware should be fixed in v2.

**Closed by TrixterTheTux** 2022-05-15 07:20 UTC
