### ISSUE TITLE
[Feature Request] Direct Login & Automatic Redirect to server panel

### ISSUE THREAD

**Issue by apyxpi** [pterodactyl/whmcs#77] opened 2020-11-03 11:08 UTC
Hello everyone

First of all, I would like to thank you for making the whmcs addon.

Secondly, I would like to request a function to add a direct login button to the user and Admin panels. The button should directly login you to the panel and then redirect you to the server. 

I think it could be done with a login "token" or with a username / password request?

In general, I think it would be very beneficial if this was implemented. 

Thanks in advance!

Kind regards,

**Comment by JakeySuccessor** [comment] 2020-11-29 06:49
Seems like a duplicate of #38

**Comment by matthewpi** [comment] 2020-11-29 17:40
Duplicate of https://github.com/pterodactyl/whmcs/issues/38

**Closed by matthewpi** 2020-11-29 17:40 UTC
